### ISSUE TITLE
user can't click the Custom RPC menu option.

### ISSUE THREAD

**Issue by frankiebee** [MetaMask/metamask-plugin#1267]
this came from slack from a user who is remotely helping someone else 

username: `mark.jackson`

no log data has yet been provided

**Comment by mjackson001** [comment]
Here are the UI State logs:

Download the React DevTools and use an HTTP server (instead of a file: URL) for a better development experience: https://fb.me/react-devtools
logState()
popup.js:95392 {
"metamask": {
"isInitialized": true,
"isUnlocked": false,
"rpcTarget": "https://rawtestrpc.metamask.io/",
"identities": {},
"unapprovedTxs": {},
"currentFiat": "USD",
"conversionRate": 50.22923497,
"conversionDate": 1490641262,
"noActiveNotices": true,
"frequentRpcList": [],
"network": "loading",
"accounts": {},
"transactions": {},
"selectedAddressTxList": [],
"unapprovedMsgs": {},
"unapprovedMsgCount": 0,
"unapprovedPersonalMsgs": {},
"unapprovedPersonalMsgCount": 0,
"keyringTypes": [
"Simple Key Pair",
"HD Key Tree"
],
"keyrings": [],
"selectedAddress": "0xa2609bc9081290ca799dfd3b8703d4231d9f5676",
"currentCurrency": "USD",
"provider": {
"type": "rpc",
"rpcTarget": "http://localhost:8545"
},
"shapeShiftTxList": [],
"lostAccounts": [],
"seedWords": "party donor august salmon bird area acid warrior birth type elephant crash"
},
"appState": {
"menuOpen": false,
"currentView": {
"name": "createVaultComplete",
"seedWords": "party donor august salmon bird area acid warrior birth type elephant crash"
},
"accountDetail": {
"subview": "transactions"
},
"transForward": true,
"isLoading": false,
"warning": null
},
"identities": {}
}
undefined

**Comment by mjackson001** [comment]
UI state logs (repost without seed words)

Download the React DevTools and use an HTTP server (instead of a file: URL) for a better development experience: https://fb.me/react-devtools
logState()
popup.js:95392 {
"metamask": {
"isInitialized": true,
"isUnlocked": false,
"rpcTarget": "https://rawtestrpc.metamask.io/",
"identities": {},
"unapprovedTxs": {},
"currentFiat": "USD",
"conversionRate": 50.22923497,
"conversionDate": 1490641262,
"noActiveNotices": true,
"frequentRpcList": [],
"network": "loading",
"accounts": {},
"transactions": {},
"selectedAddressTxList": [],
"unapprovedMsgs": {},
"unapprovedMsgCount": 0,
"unapprovedPersonalMsgs": {},
"unapprovedPersonalMsgCount": 0,
"keyringTypes": [
"Simple Key Pair",
"HD Key Tree"
],
"keyrings": [],
"selectedAddress": "0xa2609bc9081290ca799dfd3b8703d4231d9f5676",
"currentCurrency": "USD",
"provider": {
"type": "rpc",
"rpcTarget": "http://localhost:8545"
},
"shapeShiftTxList": [],
"lostAccounts": [],
"seedWords": ""
},
"appState": {
"menuOpen": false,
"currentView": {
"name": "createVaultComplete",
"seedWords": ""
},
"accountDetail": {
"subview": "transactions"
},
"transForward": true,
"isLoading": false,
"warning": null
},
"identities": {}
}
undefined

**Comment by Zanibas** [comment]
So I debugged your issue and with that current UI log, it appears the user was on the seed word screen when they attempted to set a custom RPC

we prevent users from navigating to any other screen unless they approve those seed words.

If this is the case, we can consider this closed, since we do not want people navigating around until seed words are resolved. If not, I'm going to need more information.

**Comment by mjackson001** [comment]
Thanks, I will forward that information on..

**Comment by mjackson001** [comment]
Apparently there is a dialog sizing issue.  He cannot see the "I've copied somewhere safe" button at the bottom.

![image](https://cloud.githubusercontent.com/assets/409166/24430392/8f6406ae-13d3-11e7-85e8-c3a9ef5fe142.png)

**Comment by Zanibas** [comment]
Good lord, why is that text so big...
I'll look into this.

**Comment by flyswatter** [comment]
@mjackson001 Can we get system version, browser version for that user? Haven't seen this formatting before.

**Comment by mjackson001** [comment]
![image](https://cloud.githubusercontent.com/assets/409166/24465605/df037004-146a-11e7-8193-a8802bbf0d64.png)
![image](https://cloud.githubusercontent.com/assets/409166/24465612/e5c9abc4-146a-11e7-8a36-bb3acec2a571.png)

**Comment by mjackson001** [comment]
Additional info - I know he's on a multi-headed machine (4 monitors).  I remember there was some weird Windows driver issue with Chrome that I had before so I had him try it on his primary monitor, but that did not fix the issue.

**Comment by Zanibas** [comment]
@mjackson001 what resolution is the resolution at?

**Comment by mjackson001** [comment]
Chrome version is 56.0.2924.87.  The image pasted with reduced clarity.

**Comment by mjackson001** [comment]
I've asked the question on resolution - will let you know.

**Comment by mjackson001** [comment]
All monitors are 1920x1080.

**Comment by Zanibas** [comment]
I've pushed up a change that may fix the issue--the warning label didn't have set dimensions, but have been adjusted properly. We will try to confirm this works on our end before calling this close.

**Comment by mjackson001** [comment]
should he reinstall or wait for the update?

**Comment by mjackson001** [comment]
FYI - customer confirms the latest update fixed the issue..  Thanks!

**Comment by mjackson001** [comment]
FYI - this is not completely resolved.  Customer tried to create a new account (i.e. a second account using the "+" on the switch accounts page).  He got this dialog with similar sizing issues...

![image](https://cloud.githubusercontent.com/assets/409166/24518883/8ebf5ece-1540-11e7-81fa-013e2ca0b2e6.png)

**Comment by Zanibas** [comment]
We haven't pushed up the latest change for this UI fix to production, only to master. Not sure why this was closed. We'll see if it's fixed when the next deploy happens.

**Comment by flyswatter** [comment]
A nice way to guarantee this fixes it is to make the whole view scrollable.

There's also a pretty unusual hack that you can use to work around this problem:

1. Have the affected user visit `chrome-extension://ebjbdknjcgcbchkagneicjfpneaghdhb/popup.html` (this opens the popup in a browser window).
2. Use the browser zoom commands to zoom out a few clicks. This is in the `View` menu. The zoom size on this tab should also affect the popup.

**Comment by mjackson001** [comment]
I will forward this on.  Thanks!

**Comment by ibeme2** [comment]
The Confirmation window is unusable after the last patch!
See image"
![unusable confirmation dialog](https://user-images.githubusercontent.com/30937121/29231941-140a186e-7e9e-11e7-93a0-8241381be0d4.jpg)

There is no way to resize, zoom or otherwise recover from this.

Metamask is an essential link when doing REAL transactions. When it screws up, your users cannot access funds, make transactions, cancel transactions etc. 

PLEASE DO NOT PUBLISH 'ON THE FLY' FIXES THAT HAVE NOT BEEN PROPERLY TESTED ! ! ! !

**Comment by meow0703** [comment]
Please help check, i cannot click on the custom rpc menu both on Chrome and Firefox
Chrome: Version 62.0.3202.94 (Official Build) (64-bit)
Firefox: 57.0.1 (64-bit)
OS: Ubuntu 17 (64-bit)
Tons of thanks
